//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_III_Milos_Peric
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeDatabaseEntities : DbContext
    {
        public RecipeDatabaseEntities()
            : base("name=RecipeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblIngredient> tblIngredients { get; set; }
        public virtual DbSet<tblRecipe> tblRecipes { get; set; }
        public virtual DbSet<tblRecipeIngredient> tblRecipeIngredients { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
