//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_III_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIngredient()
        {
            this.tblRecipeIngredients = new HashSet<tblRecipeIngredient>();
        }
    
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<int> IngredientAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecipeIngredient> tblRecipeIngredients { get; set; }
    }
}
