//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_III_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipeIngredient
    {
        public int RecipeIngredientID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual tblIngredient tblIngredient { get; set; }
        public virtual tblRecipe tblRecipe { get; set; }
    }
}
